import type { Metadata } from "next";
import { Inter, Chivo } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const chivo = Chivo({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "die-immobilienankäufer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(chivo.className, "")}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
