CONTENTFUL_ACCESS_TOKEN         = "nHI89Ue4AxEEGaC_8FVqStJKGWNxdBk7Q5po7_7qctg"
CONTENTFUL_CMA_TOKEN            = "CFPAT-GKz16V8JGJ7URpb2jAVBxegrGiJOlZ-ukQk278vxa_o"
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = "AIzaSyBCFfpZu1SOvYC9izf5qu3aw_LVtcKjKEo"
RESEND_API_KEY                  = "re_7yERFkA2_9McN3Bq8fvLSvFniRBP5TuVX"
# EDGESTORE
EDGE_STORE_ACCESS_KEY = "hSo5SyGulSCHCB2026lC9HvnhmJMqNch"
EDGE_STORE_SECRET_KEY = "yJsAOSn3TBzyEteFgh9SrEUzoiaWhR2E3OYH9VHa3IcH2tze"
